const apiUrl = 'https://api-hospital.fhn.gov.az/api/v1'; 
export const environment = {
  production: false, 
  getHomePagesUrl: `${apiUrl}/HomePages`,
  getFooterUrl: `${apiUrl}/FooterPages/GetWithLang`,
  getDepartmentsUrl:`${apiUrl}/Departments/GetListWithLang`,
  getDoctorsUrl:`${apiUrl}/Doctors/GetListWithLang`,
  getNewsUrl:`${apiUrl}/News/GetLastNewsByCountWithLang`,
  getTestimonialsUrl:`${apiUrl}/FeedbackAndSuggestions`,
  getAdvertisementUrl:`${apiUrl}/Advertisements/GetLastAdvertisementsByCountWithLang`,
  getAchievementsUrl:`${apiUrl}/Achievements/GetListWithLang`,
  getAcknowledgementsUrl:`${apiUrl}/Acknowledgements/GetListWithLang`,
  getAboutsUrl:`${apiUrl}/Abouts/GetListWithLang`,
  getContactsUrl:`${apiUrl}/Contacts/GetWithLang`,
  getFeedbackAndSuggestionsUrl:`${apiUrl}/FeedbackAndSuggestions`,
  getFeedbackAndSuggestionsPagesUrl:`${apiUrl}/FeedbackAndSuggestionsPages/GetWithLang`,
  getGalleryCategoriesUrl:`${apiUrl}/GalleryCategories`,
  getGalleryTypesUrl:`${apiUrl}/GalleryTypes/GetListWithLang`,
  getUsefulLinksUrl:`${apiUrl}/UsefulLinks/GetListWithLang`,
};
